# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color:rgb(255,250,250)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_select = QtWidgets.QComboBox(self.centralwidget)
        self.name_select.setGeometry(QtCore.QRect(270, 240, 200, 30))
        self.name_select.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0.2);\n"
"}")
        self.name_select.setObjectName("name_select")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(140, 240, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.aim_label = QtWidgets.QLabel(self.centralwidget)
        self.aim_label.setGeometry(QtCore.QRect(140, 300, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.aim_label.setFont(font)
        self.aim_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.aim_label.setAlignment(QtCore.Qt.AlignCenter)
        self.aim_label.setObjectName("aim_label")
        self.rbw_label = QtWidgets.QLabel(self.centralwidget)
        self.rbw_label.setGeometry(QtCore.QRect(210, 390, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.rbw_label.setFont(font)
        self.rbw_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.rbw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rbw_label.setObjectName("rbw_label")
        self.aim_select = QtWidgets.QComboBox(self.centralwidget)
        self.aim_select.setGeometry(QtCore.QRect(270, 300, 200, 30))
        self.aim_select.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0.2);\n"
"}")
        self.aim_select.setObjectName("aim_select")
        self.color_label = QtWidgets.QLabel(self.centralwidget)
        self.color_label.setGeometry(QtCore.QRect(210, 560, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.color_label.setFont(font)
        self.color_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.color_label.setObjectName("color_label")
        self.b_label = QtWidgets.QLabel(self.centralwidget)
        self.b_label.setGeometry(QtCore.QRect(270, 450, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.b_label.setFont(font)
        self.b_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.b_label.setAlignment(QtCore.Qt.AlignCenter)
        self.b_label.setObjectName("b_label")
        self.w_label = QtWidgets.QLabel(self.centralwidget)
        self.w_label.setGeometry(QtCore.QRect(370, 450, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.w_label.setFont(font)
        self.w_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.w_label.setAlignment(QtCore.Qt.AlignCenter)
        self.w_label.setObjectName("w_label")
        self.r_lable = QtWidgets.QLabel(self.centralwidget)
        self.r_lable.setGeometry(QtCore.QRect(170, 450, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.r_lable.setFont(font)
        self.r_lable.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.r_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.r_lable.setObjectName("r_lable")
        self.r_num = QtWidgets.QTextEdit(self.centralwidget)
        self.r_num.setGeometry(QtCore.QRect(210, 450, 50, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.r_num.setFont(font)
        self.r_num.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.r_num.setObjectName("r_num")
        self.b_num = QtWidgets.QTextEdit(self.centralwidget)
        self.b_num.setGeometry(QtCore.QRect(310, 450, 50, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.b_num.setFont(font)
        self.b_num.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.b_num.setObjectName("b_num")
        self.w_num = QtWidgets.QTextEdit(self.centralwidget)
        self.w_num.setGeometry(QtCore.QRect(410, 450, 50, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.w_num.setFont(font)
        self.w_num.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.w_num.setObjectName("w_num")
        self.color_num = QtWidgets.QTextEdit(self.centralwidget)
        self.color_num.setGeometry(QtCore.QRect(340, 613, 50, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.color_num.setFont(font)
        self.color_num.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.color_num.setObjectName("color_num")
        self.color_num_label = QtWidgets.QLabel(self.centralwidget)
        self.color_num_label.setGeometry(QtCore.QRect(220, 610, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.color_num_label.setFont(font)
        self.color_num_label.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.color_num_label.setAlignment(QtCore.Qt.AlignCenter)
        self.color_num_label.setObjectName("color_num_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1201, 127))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.layoutWidget)
        self.title.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.subtitle = QtWidgets.QLabel(self.layoutWidget)
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.verticalLayout.addWidget(self.subtitle)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(670, 160, 450, 550))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(20)
        self.splitter_2.setObjectName("splitter_2")
        self.attr_label = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_label.sizePolicy().hasHeightForWidth())
        self.attr_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.attr_label.setFont(font)
        self.attr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.attr_label.setObjectName("attr_label")
        self.background2 = QtWidgets.QLabel(self.splitter_2)
        self.background2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.background2.sizePolicy().hasHeightForWidth())
        self.background2.setSizePolicy(sizePolicy)
        self.background2.setStyleSheet("*{\n"
"background-color: rgba(202,255,112,0.2);\n"
"border-radius:20px\n"
"}")
        self.background2.setText("")
        self.background2.setObjectName("background2")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(750, 230, 300, 300))
        self.picture.setStyleSheet("*{\n"
"border: 2px solid rgba(205,92,92,0.5);\n"
"background-color: rgba(202,255,112,0);\n"
"}")
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setGeometry(QtCore.QRect(550, 430, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.calculate.setFont(font)
        self.calculate.setObjectName("calculate")
        self.member = QtWidgets.QLabel(self.centralwidget)
        self.member.setGeometry(QtCore.QRect(250, 810, 70, 20))
        self.member.setObjectName("member")
        self.function_descrip = QtWidgets.QLabel(self.centralwidget)
        self.function_descrip.setGeometry(QtCore.QRect(560, 810, 70, 20))
        self.function_descrip.setObjectName("function_descrip")
        self.develop_info = QtWidgets.QLabel(self.centralwidget)
        self.develop_info.setGeometry(QtCore.QRect(870, 810, 70, 20))
        self.develop_info.setObjectName("develop_info")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(80, 160, 450, 550))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(20)
        self.splitter.setObjectName("splitter")
        self.para_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.para_label.sizePolicy().hasHeightForWidth())
        self.para_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.para_label.setFont(font)
        self.para_label.setAlignment(QtCore.Qt.AlignCenter)
        self.para_label.setObjectName("para_label")
        self.background1 = QtWidgets.QLabel(self.splitter)
        self.background1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.background1.sizePolicy().hasHeightForWidth())
        self.background1.setSizePolicy(sizePolicy)
        self.background1.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0.2);\n"
"border-radius:20px\n"
"}")
        self.background1.setText("")
        self.background1.setObjectName("background1")
        self.vertice_num = QtWidgets.QLabel(self.centralwidget)
        self.vertice_num.setGeometry(QtCore.QRect(800, 550, 200, 35))
        self.vertice_num.setStyleSheet("*{\n"
"border: 1px solid rgba(0,0,0,0.5);\n"
"background-color: rgba(202,255,112,0);\n"
"}")
        self.vertice_num.setText("")
        self.vertice_num.setAlignment(QtCore.Qt.AlignCenter)
        self.vertice_num.setObjectName("vertice_num")
        self.edge_num = QtWidgets.QLabel(self.centralwidget)
        self.edge_num.setGeometry(QtCore.QRect(800, 600, 200, 35))
        self.edge_num.setStyleSheet("*{\n"
"border: 1px solid rgba(0,0,0,0.5);\n"
"background-color: rgba(202,255,112,0);\n"
"}")
        self.edge_num.setText("")
        self.edge_num.setAlignment(QtCore.Qt.AlignCenter)
        self.edge_num.setObjectName("edge_num")
        self.surface_num = QtWidgets.QLabel(self.centralwidget)
        self.surface_num.setGeometry(QtCore.QRect(800, 650, 200, 35))
        self.surface_num.setStyleSheet("*{\n"
"border: 1px solid rgba(0,0,0,0.5);\n"
"background-color: rgba(202,255,112,0);\n"
"}")
        self.surface_num.setText("")
        self.surface_num.setAlignment(QtCore.Qt.AlignCenter)
        self.surface_num.setObjectName("surface_num")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(300, 730, 600, 50))
        self.result.setStyleSheet("*{\n"
"border: 2px solid rgba(0,0,0,0.5);\n"
"border-radius:20px;\n"
"}")
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(110, 390, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 560, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("*{\n"
"background-color: rgba(141,238,238,0);\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.splitter_2.raise_()
        self.splitter.raise_()
        self.layoutWidget.raise_()
        self.name_select.raise_()
        self.name_label.raise_()
        self.aim_label.raise_()
        self.rbw_label.raise_()
        self.aim_select.raise_()
        self.color_label.raise_()
        self.b_label.raise_()
        self.w_label.raise_()
        self.r_lable.raise_()
        self.r_num.raise_()
        self.b_num.raise_()
        self.w_num.raise_()
        self.color_num.raise_()
        self.color_num_label.raise_()
        self.picture.raise_()
        self.calculate.raise_()
        self.member.raise_()
        self.function_descrip.raise_()
        self.develop_info.raise_()
        self.vertice_num.raise_()
        self.edge_num.raise_()
        self.surface_num.raise_()
        self.result.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "多面体名字"))
        self.aim_label.setText(_translate("MainWindow", "染色目标"))
        self.rbw_label.setText(_translate("MainWindow", "【指定三种颜色组合】"))
        self.color_label.setText(_translate("MainWindow", "【指定总颜色数】"))
        self.b_label.setText(_translate("MainWindow", "蓝"))
        self.w_label.setText(_translate("MainWindow", "白"))
        self.r_lable.setText(_translate("MainWindow", "红"))
        self.color_num_label.setText(_translate("MainWindow", "颜色总数"))
        self.title.setText(_translate("MainWindow", "多面体染色计数"))
        self.subtitle.setText(_translate("MainWindow", "2020组合数学作业"))
        self.attr_label.setText(_translate("MainWindow", "多面体属性"))
        self.calculate.setText(_translate("MainWindow", "计算"))
        self.member.setText(_translate("MainWindow", "小组成员"))
        self.function_descrip.setText(_translate("MainWindow", "功能说明"))
        self.develop_info.setText(_translate("MainWindow", "开发信息"))
        self.para_label.setText(_translate("MainWindow", "参数选择"))
        self.radioButton.setText(_translate("MainWindow", "模式一"))
        self.radioButton_2.setText(_translate("MainWindow", "模式二"))
